# Generated by Django 4.1.7 on 2023-03-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(max_length=200, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="content",
            name="snippet",
            field=models.TextField(null=True, verbose_name="Code Snippet"),
        ),
        migrations.AlterField(
            model_name="content",
            name="text",
            field=models.TextField(null=True, verbose_name="Plain Text"),
        ),
    ]
