# Generated by Django 4.1.7 on 2023-03-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0003_alter_content_snippet_alter_content_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(blank=True, max_length=200, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="content",
            name="snippet",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="Code Snippet"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="text",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="Plain Text"
            ),
        ),
    ]
